/**
 * Emit `dist/compliance-words-keyset.json` — the cross-language keyset that the
 * Python Report-Engine (P3) vendors with a CI freshness diff (Guard-Kit §7).
 * Runs as a tsup `onSuccess` step, after `dist/index.js` is built.
 *
 * Unlike the signals keyset (a flat list of exact keys + family prefixes), the
 * compliance keyset must carry the FULL vocabulary AND the context model, because
 * the load-bearing logic is the context-aware matcher, not a membership test. The
 * Python consumer re-implements `check_compliance` over this keyset — so it ships
 * every field the matcher needs: forms, matchType, category, allowedContexts
 * (kind/pattern/proximity/note), suggest, provenance, the negation cue list, and
 * the default negation proximity.
 *
 * Deterministic by construction (stable field order, no timestamp) because
 * `dist/` is committed to git — a non-deterministic field would churn the diff on
 * every build.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const {
  COMPLIANCE_REGISTRY,
  NEGATION_CUES,
  DEFAULT_NEGATION_PROXIMITY,
  DEFAULT_LIST_NEGATION_PROXIMITY,
  CLAUSE_BREAKERS,
  LIST_COORDINATORS,
  LANE_REGISTRY,
} = await import(join(root, "dist", "index.js"));
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

// Serialize the registry with a stable, explicit field order (do NOT spread the
// entry object — key order would then depend on source-literal order and churn).
const entries = COMPLIANCE_REGISTRY.map((e) => ({
  token: e.token,
  matchType: e.matchType,
  forms: [...e.forms],
  category: e.category,
  allowedContexts: e.allowedContexts.map((c) => ({
    kind: c.kind,
    pattern: c.pattern,
    ...(c.proximity === undefined ? {} : { proximity: c.proximity }),
    note: c.note,
  })),
  ...(e.suggest === undefined ? {} : { suggest: e.suggest }),
  provenance: [...e.provenance],
}));

// Serialize the lane registry (DRAFT, warn-only) with the same stable field
// order. The lane rows ride the SAME matching contract + allowedContexts model
// as the M7 entries (they only add `lane` + `severity`), so a Python consumer
// re-implements `scan_lane_violations` over the same shared algorithm — no new
// matcher. Emitted as a SEPARATE `laneEntries` block so a v0.1.2-era consumer
// that only reads `entries` is unaffected (additive).
const laneEntries = LANE_REGISTRY.map((e) => ({
  token: e.token,
  lane: e.lane,
  matchType: e.matchType,
  forms: [...e.forms],
  severity: e.severity,
  allowedContexts: e.allowedContexts.map((c) => ({
    kind: c.kind,
    pattern: c.pattern,
    ...(c.proximity === undefined ? {} : { proximity: c.proximity }),
    note: c.note,
  })),
  rationale: e.rationale,
  ...(e.suggest === undefined ? {} : { suggest: e.suggest }),
}));

const keyset = {
  $comment:
    "GENERATED by scripts/emit-keyset.mjs at build (tsup onSuccess) — do not edit by hand. Cross-language keyset for the Python Report-Engine consumer (Guard-Kit §7). Carries the full M7 vocabulary + context model so check_compliance can be re-implemented identically. Matching contract: word-stem/word forms match at word boundaries (case-sensitive for matchType 'word' = AI); phrase forms match the ordered word sequence with intervening non-word chars; a token is a violation unless an allowedContext fires (negation cue within `proximity` words before the match in the same clause — OR within `listNegationProximity` words when a comma/`or`/`nor` coordinator lies between the cue and the match, the negation scan stopping at a sentence terminator or a `clauseBreakers` word | match inside a compound `pattern` | match offset inside a caller-supplied disclaimer range). `laneEntries` (DRAFT, warn-only) ride the SAME matching contract; a lane row is reported only when its `lane` is out-of-lane for the caller's role (AGENT→AGENT_LANE_VIOLATION, MLO→MLO_LANE_VIOLATION, DUAL→none).",
  package: pkg.name,
  version: pkg.version,
  negationCues: [...NEGATION_CUES],
  defaultNegationProximity: DEFAULT_NEGATION_PROXIMITY,
  listNegationProximity: DEFAULT_LIST_NEGATION_PROXIMITY,
  clauseBreakers: [...CLAUSE_BREAKERS],
  listCoordinators: [...LIST_COORDINATORS],
  sentenceTerminators: [".", "!", "?", ";", "\n"],
  entries,
  laneConfig: {
    status: "DRAFT",
    defaultSeverity: "WARNING",
    armed: false,
    roleLaneMap: {
      AGENT: ["AGENT_LANE_VIOLATION"],
      MLO: ["MLO_LANE_VIOLATION"],
      DUAL: [],
    },
  },
  laneEntries,
};

const outPath = join(root, "dist", "compliance-words-keyset.json");
writeFileSync(outPath, `${JSON.stringify(keyset, null, 2)}\n`, "utf8");

console.log(
  `[emit-keyset] wrote ${outPath} — ${entries.length} entries, ${laneEntries.length} lane entries (DRAFT), ${NEGATION_CUES.length} negation cues (v${pkg.version})`,
);
